### PR TITLE
Add match-mappings support

### PR DESCRIPTION
**Pull request by yehuohan**
An example with text:

`HopChar1` with `s`:

### CODE REVIEW

**Comment by phaazon** [comment]
Can you describe the problem / how you solved it? It’s a bit unclear from my perspective.

**Comment by yehuohan** [comment]
> Can you describe the problem / how you solved it? It’s a bit unclear from my perspective.

Of course.
I would like to take this PR as a feature to extend the search space.

- What does this PR to do:

Still with the example text:

a

 When run `HopChar1` with `s` without this PR, only `s` from English words `test` and `mappings` can be found like below:
 
c

But for Chinese word, `s` can represent the `试` too in PinYin. So with this PR, `s` will search Chinese word too like below:

b

- How to implement:

When `Hop` with `s`, `jump_target.regex_by_case_searching` will search with regex `s`. And this PR will generate the regext `[s试]` to search according to the configuration `M.match_mappings`. To extend to other search space for other lanuage, we just add a dict like the files under `lua/hop/mappings/*.lua`

**Comment by phaazon** [comment]
The feature is interesting but nothing has happened lately so closing for stale PR. Feel free to reopen with the conflicts fixed.

**Comment by yehuohan** [comment]
> The feature is interesting but nothing has happened lately so closing for stale PR. Feel free to reopen with the conflicts fixed.

@phaazon  I have fixed the conflicts of the PR branch [match-mappings](https://github.com/yehuohan/hop.nvim/tree/match-mappings).  Can you have a review on this PR? (It seems there is no button to click to reopen for me. Can you help to reopen this PR? Or I need to submit another PR?)

**Pull request closed without merging**
