### PR TITLE
Unicode cursor location fix

### LINKED ISSUE #245: Bug using HopWord1CurrentLineAC and BC with Unicode text
Awesome plugin :sunglasses: 

It's really useful for editing Cyrillic text - there I can't get by using `f` and `t` except for punctuation.

There is a bug with the `HopWord1CurrentLineAC` when starting from a non-initial column - the highlighting starts missing the first words, and it starts appearing in the middle of the rest. At some point it stops working alltogether and reports a `there's no such thing we can see` error. In the example I use hop -> d for a line in Latin and a line in Cyrillics:

nvim-hop bug

Here's my mapping:
```vim
vim.api.nvim_set_keymap('n', '<leader>l', "<cmd> lua require'hop'.hint_words({ direction = require'hop.hint'.HintDirection.AFTER_CURSOR, current_line_only = true  })<cr>", {})
```

From what I can tell `hint_words` works well, then `hint_words` on current line also is ok, but if I add after or before cursor it seems to have a wrong read on where the cursor is, i.e. in this case it thinks it's on `им*а*` and it's on `*н*а` (the `им*а*` is highlighted):

nvim-hop bug 2

### PR DESCRIPTION
**Pull request by gerazov**
Closes #245

### CODE REVIEW

**Comment by phaazon** [comment]
Can you describe why you can’t use the Lua API? I’m not really fond of using the “old” Vim way.

**Comment by gerazov** [comment]
Yeah :smile: the nvim api doesn't return the virtcol atm. I mentioned this in an existing issue over there https://github.com/neovim/neovim/issues/12973

This is still not ready to merge - I've seen some bugs with empty lines and when the cursor is at the end of line with the change to virtcol. I'll try and fix them up and give you a heads up :+1:

**Comment by gerazov** [comment]
There's a bug with end of lines and empty lines in this that needs to be fixed ...

**Comment by numToStr** [comment]
Today, I've hit the *empty line* issue numerous times #261. Is it possible to revert this for the time being?

**Pull request merged**
