### PR TITLE
Feature/additional motions take2

### PR DESCRIPTION
**Pull request by jhgarner**
This adds all of the motions that were included in the original pull request. The code is heavily refactored and shouldn't include any breaking changes.

#59 should probably be merged in first but I'm opening this request now in case you want to see the end result. Hopefully this is the right way to split up the work but let me know if that's not the case.

### CODE REVIEW

**Comment by weilbith** [comment]
I'm really awaiting this. Are there any updates for it?

**Comment by jhgarner** [comment]
I'm waiting on a response to #59 which needs to be finished first. After that, I can rebase this request and hopefully it'll be merged soon after.

It's pretty easy to get something like Plug to use a different fork/branch in case you want to test this before it's merged.

**Comment by weilbith** [comment]
> It's pretty easy to get something like Plug to use a different fork/branch in case you want to test this before it's merged.

True. Maybe I should try that as long as there are no other crucial merges in-between 😬 
So does this PR work on top of #59 or can I go straight for this feature branch here?

**Comment by jhgarner** [comment]
You should be able to go straight for this feature branch. I'm not sure if it was the right way to do it, but this branch includes the commits from the other.

**Comment by phaazon** [comment]
Thanks for the PR. Unfortunately, I’m going to close this, as the initial PR you based your work from was superseded by #93, which brings in most of the commands you implemented here.

**Pull request closed without merging**
