### PR TITLE
fix: pending operation col increment

### PR DESCRIPTION
**Pull request by ChristianChiarulli**
I think this is the desired behavior for any pending operation destination

Jumping backwards seems to already works fine (it leaves out the character you jump from but that is already how vim works)
Jumping forwards needs to be incremented if done from a pending operation context

### CODE REVIEW

**Comment by tobealive** [comment]
Backwards motions using `hint_offset` are impaired:

`E5107: Error loading lua [string ":lua"]:1: '}' expected near 'hint_offset'`

**Comment by lmburns** [comment]
What I had done as a partial fix for `t` and `T` in both normal and `x` mode is this:

```lua
map(
    "n",
    "t",
    function()
        require("hop").hint_char1(
            {
                direction = require("hop.hint").HintDirection.AFTER_CURSOR,
                current_line_only = true
            }
        )
        local tc = api.nvim_replace_termcodes("h", true, false, true)
        api.nvim_feedkeys(tc, "n", false)
    end
)

map(
    "n",
    "T",
    function()
        require("hop").hint_char1(
            {
                direction = require("hop.hint").HintDirection.BEFORE_CURSOR,
                current_line_only = true,
                inclusive_jump = false
            }
        )
        local tc = api.nvim_replace_termcodes("l", true, false, true)
        api.nvim_feedkeys(tc, "n", false)
    end
)
```

Because the `t` characters move on top of the destination character.

After one of the later commits, I've noticed that the `f` character is now messed up in operator-pending mode, which I had as this previously, and now no longer works as expected.

```lua
map(
    "o",
    "f",
    function()
        require("hop").hint_char1(
            {
                direction = require("hop.hint").HintDirection.AFTER_CURSOR,
                current_line_only = true,
                inclusive_jump = true -- Both true and false don't work
            }
        )
    end
)
```

**Comment by phaazon** [comment]
I’d rather fix that by not overloading that function. Your fix is fine but not located at the right place, so I’m going to make the change because it’s annoying, agreed.

**Comment by phaazon** [comment]
Yeah actually I think it’s fine. Thanks!

**Review by phaazon — APPROVED** [review]

**Pull request merged**
