### PR TITLE
Migemo feature

### PR DESCRIPTION
**Pull request by delphinus**
[Migemo feature][] is a key feature of [vim-easymotion][] for Japanese. This enables users to search “2-byte” characters (Hiragana, Katakana, Kanji) without switching input methods.

[Migemo feature]: https://github.com/easymotion/vim-easymotion#migemo-feature-for-japanese-user
[vim-easymotion]: https://github.com/easymotion/vim-easymotion

https://user-images.githubusercontent.com/1239245/123513304-8568b580-d6c7-11eb-9f57-e1e3eb4d6583.mp4

I implemented with reference to easymotion's one. All features will be enabled only in `use_migemo = true`.

* for `HopChar1`
  - It calculates regexp with the table defined in `hop.nvim` source.
* for `HopChar2`
  - It invokes [cmigemo][] binary and fetch regexp.
* ~for `HopPattern` (not implemented yet)~
  - It invokes [cmigemo][] binary and fetch regexp.
  - I decided not to implement this (see below).

[cmigemo]: https://github.com/koron/cmigemo

So for doing this with `HopChar2` or `HopPattern`, users should install `cmigemo` for dependencies. (You can do `brew install cmigemo` for macOS)

I wonder that I wrote much codes for process invoking (`process.lua`). Can I merge into here? or separate repo such as `hop-migemo.nvim`? Do you have any thoughts?

### CODE REVIEW

**Comment by phaazon** [comment]
Supporting input method billions of people use makes total sense, so yes, it has its place on this repository. I am not used to migemo though, so I need to understand a bit more. 

> This enables users to search “2-byte” characters (Hiragana, Katakana, Kanji) without switching input methods.

What does that mean? `:HopWord` does what it means: it searches words. Its behavior shouldn’t change. However, searching for two-byte characters, if I understand correctly, seems like a good idea. Now, do we really need to pull a dependency for that? Can we not simply use an implementation similar to `:HopChar2` (i.e. two `getchar`, basically)?

**Comment by delphinus** [comment]
I noticed some highlights are not shown especially for long sentences containing many multi-byte characters. I look into it further...

**Comment by delphinus** [comment]
@phaazon  Sorry for too late. Finally I can re-review my code and I almost satisfy its working. Please review.

NOTE:

* I decided `:HopPattern` should not support migemo. `cmigemo` does not support Kanji but Katakana/Hiragana only for 3 or more characters probably because the regexp will be extremely long. `HopChar1` and `HopChar2` are enough for almost use, I think.
* I rebased to the latest master and re-captured a movie above.

**Comment by phaazon** [comment]
Sorry @delphinus, can you rebase so that we can finally merge this? If you don’t have time for it I will understand, since it’s been a while and I haven’t been very disciplined with reviewing Hop PRs lately.

**Comment by delphinus** [comment]
I see. Later I will check and rebase this. Maybe in weekend.

**Pull request closed without merging**
