### PR TITLE
added a cursorline flag and automatic toggling when entering/exiting hop

### PR DESCRIPTION
**Pull request by BlakeJC94**
This small fix does what it says on the tin: 
- `create_hint_state` now saves the users state of the `cursorline` option
- `add_virt_cur` disables cursorline if true
- if `cursorline` is true, disable it temporarily in `add_virt_cur`, restore users cursorline state from `hint_state` in `quit`

The reason I made this fix was because the highlighting in Hop looks slightly strange if you have `cursorline` highlighting set to be a solid background color (instead of the default underline), see attached image below

hop_cursorline_issue

I've done some testing on my end for this small fix, but might be worth someone else having a look as well :)

EDIT: uploaded clearer screenshot of issue

### CODE REVIEW

**Comment by phaazon** [comment]
Can you rebase so that we can merge this? Thanks.

**Comment by megalithic** [comment]
@BlakeJC94 would love to have this merged. would you mind rebasing to resolve conflicts?

**Comment by BlakeJC94** [comment]
Hello! Apologies for the delayed response. I've rebased the latest changes, but looks like there's a merge conflict in `init.lua`. Should hopefully be a relatively quick fix

**Comment by BlakeJC94** [comment]
@megalithic @phaazon Should be all good to go now. Cleaned up my code so this PR changes the least amount of functions (by caching cursorine state in `hint_state`). Let me know if there's anything else I can help with

**Review by phaazon — APPROVED** [review]
Thank you!

**Pull request merged**
