### PR TITLE
Add highlighting to show where the cursor was before a hop

### PR DESCRIPTION
**Pull request by brphilly**
The first commit is a general refactoring of the grey/hints highlighting to use the priority key when creating an extmark. An advantage of this method is that you don't have to grey everything out every time the hints are refined. This is similar to #62 except I went further with the refactoring and also explained how the priority key works by looking at neovims source code. This commit also made it easier to add the next commit.

The second commit adds a "virtual cursor" when hopping by putting virtual text of a unicode block character where the cursor was located before hopping. This makes it easy to see where the cursor was when you started the hop.

One caveat of this is that it blocks the character underneath the virtual cursor however this should be fine as the user won't need to hop to where the cursor already was.

Another thing to note is that I'm not sure what happens if the users font cannot display the unicode block character. I assume it displays some kind of question mark instead although I haven't been able to confirm this as every font I tried that was already installed on MacOS displayed the block character without issue. As such I don't expect this to be a problem, especially among users of neovim.

It would also be fairly easy to let the user decide in the config which character and highlight group to use to signify where the cursor was. I haven't added this because I don't know whether you like this idea or whether it might create too many configuration options that could overwhelm users.
hop-virt-cur

### CODE REVIEW

**Comment by folke** [comment]
Instead of virtual text, you can simply highlight the cursor with the `Cursor` group to create a fake cursor. This way, the character is still visible as before.

Is do this [here](https://github.com/folke/which-key.nvim/blob/167661151204ea7da2d365113a76ab223b3dc880/lua/which-key/view.lua#L116) for **WhichKey**

**Comment by bphilly96** [comment]
@folke Not sure how I didn't think of this, thanks for mentioning it! I'll change this later today.

**Comment by phaazon** [comment]
Do you mind rebasing and fixing the conflicts? I’m interested in that PR.

**Comment by folke** [comment]
Should probably also fix the fake cursor as mentioned above

**Comment by bphilly96** [comment]
@phaazon This one should be good to go as well. Thanks again @folke for the better fake cursor idea.

**Comment by ggandor** [comment]
@folke `nvim_buf_add_highlight` does not work if the cursor is currently on an empty line, so it might be better to use an extmark in which-key too
@bphilly96 a plain extmark, however, is even worse, as this will throw a "col value outside range" error, so I guess the original virtualtext idea is the one to go with. (I've already [ran into this edge case](https://github.com/ggandor/lightspeed.nvim/blob/main/fnl/lightspeed.fnl#L287) with Lightspeed.)

**Comment by bphilly96** [comment]
@ggandor Thanks for the heads up. Turns out this is also an issue if the `virtualedit` option is being used and the cursor is past the end of the line or inside a tab character. I've now made it so that a highlight is used when on a character so that the character beneath can still be seen, and a virtual-text block character is used otherwise.

I also found out that the virtual cursor wouldn't show if the cursor was on a multibyte character but I think I've fixed that too.

**Comment by bphilly96** [comment]
I've done some more tinkering to try and fix a couple of issues. This PR should now fix #99 but doesn't seem to fix #76. This is because the highlights in #76 are setting the background colour whereas in `HopUnmatched` no background colour is set. This means that even though the grey highlights have a higher priority, only the foreground is greyed out.

One way to solve this would be to set a background colour in `HopUnmatched` however this would remove the transparency when hopping for any users who are using a transparent background .

**Comment by phaazon** [comment]
> One way to solve this would be to set a background colour in `HopUnmatched` however this would remove the transparency when hopping for any users who are using a transparent background .

Yeah, that’s not ideal, and even for users using opaque editors (like me): we don’t want to switch to a different color. A possible way would be to use I-don’t-recall-which-Lua-function to query the `bg` of `NonText` / `Normal` and use the same in `HopUnmatched`, but that seems rather hacky.

I’ll have a look at your PR ASAP.

**Comment by brphilly** [comment]
I have added `guibg=bg` to `HopUnmatched`. This should fix #76 for anyone who has set `guibg` in `Normal`. If you haven't (i.e. people using transparent backgrounds) then you will still see background highlights in situations like #76 but I'm not sure there's an easy fix.

I tried to do the same with `ctermbg=bg` however this would throw an error if there was no `ctermbg` set in `Normal` so I removed it. This means #76 is also still an issue for anyone using `notermguicolors`.

**Comment by synaptiko** [comment]
@brphilly Thanks for this work, I just switched to it and it's feels better than the default behavior. Is there a way to make it work also for `:HopChar*`?

**Comment by brphilly** [comment]
@synaptiko I have made the virtual cursor appear when using `:HopChar*` and `:HopPattern`.

I also linked `HopCursor` to `Cursor` by default as this seems like a more sensible default compared to what was there before.

**Pull request merged**
